version: "3.9"

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env.docker
    restart: unless-stopped
    networks:
      - urlshortener
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  urlshortener:
    driver: bridge